parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Blackator\Bundle\VediMenuBundle\Twig\VediMenuTwigExtension: ~
  Blackator\Bundle\VediMenuBundle\Loaders\YamlMenuLoader: ~