parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Blackator\Bundle\VediMenuBundle\MenuGenerator\MenuGenerator: ~
  Blackator\Bundle\VediMenuBundle\Twig\VediMenuTwigExtension: ~